
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://15.165.18.66:3306/homerDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ssafy

  jpa:
    #open-in-view: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      #show-sql: true
  redis:
   port: 6379
   host: 15.165.18.66
   
   
cloud:
  aws:
    credentials:
      accessKey: AKIA3RPMVVCHL7EJI6PW
      secretKey: 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
    s3:
      bucket: chatzipt
    region:
      static: ap-northeast-2
    stack:
      auto: false
