
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.201.45.143:3306/homerDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ssafy

  jpa:
    #open-in-view: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      #show-sql: true
  redis:
   port: 6379
   host: 43.201.45.143
   
   
cloud:
  aws:
    credentials:
      accessKey: *
      secretKey: *
    s3:
      bucket: chatzipt
    region:
      static: ap-northeast-2
    stack:
      auto: false
