version: '3.8'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis-master.conf:/etc/redis/redis.conf
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    networks:
      - redis-net

  redis-slave-1:
    image: redis:latest
    container_name: redis-slave-1
    depends_on:
      - redis-master
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf", "--replicaof", "redis-master", "6379"]
    ports:
      - "6380:6379"
    networks:
      - redis-net

  redis-slave-2:
    image: redis:latest
    container_name: redis-slave-2
    depends_on:
      - redis-master
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf", "--replicaof", "redis-master", "6379"]
    ports:
      - "6381:6379"
    networks:
      - redis-net

  sentinel-1:
    image: redis:latest
    container_name: sentinel-1
    depends_on:
      - redis-master
    volumes:
      - ./sentinel/:/etc/sentinel/
    command: ["redis-server", "/etc/sentinel/sentinel1.conf", "--sentinel"]
    ports:
      - "26379:26379"
    networks:
      - redis-net

  sentinel-2:
    image: redis:latest
    container_name: sentinel-2
    depends_on:
      - redis-master
    volumes:
      - ./sentinel:/etc/sentinel/
    command: [ "redis-server", "/etc/sentinel/sentinel2.conf", "--sentinel" ]
    ports:
      - "26380:26379"
    networks:
      - redis-net

  sentinel-3:
    image: redis:latest
    container_name: sentinel-3
    depends_on:
      - redis-master
    volumes:
      - ./sentinel:/etc/sentinel/
    command: [ "redis-server", "/etc/sentinel/sentinel3.conf", "--sentinel" ]
    ports:
      - "26381:26379"
    networks:
      - redis-net

networks:
  redis-net: